Instance: BBEobPharmacy
InstanceOf: CARINBBExplanationOfBenefitPharmacy
Description: "BBEoB from Jeff"
* meta.versionId = "1"
* meta.lastUpdated = "2020-07-23T16:04:04.584-04:00"
* meta.source = "#2Htk0DNoUEbccjg0"
* meta.profile[0] = Canonical(CARINBBExplanationOfBenefitPharmacy)
* identifier.value = "7d0c2c7f-8049-445a-a283-41cf91d09a38"
* identifier.system = "https://bluebutton.cms.gov/resources/variables/clm_id"
* identifier.use = #official
* identifier.type = IdentifierTypeCS#cn 
* use = #claim 
* status = #active
* type.coding[0].system = "http://terminology.hl7.org/CodeSystem/claim-type"
* type.coding[0].code = #pharmacy
* type.coding[0].display = "PHARMACY"
* patient.reference = "Patient/64"
* patient.display = "Alice Dominguez Gibson"
* billablePeriod.start = "2019-01-18T15:40:00-05:00"
* billablePeriod.end = "2020-01-18T15:40:00-05:00"
* created = "2019-01-18T16:00:00-05:00"
* insurer.reference = "Organization/9"
* insurer.display = "SilverCaid"
* payee.type.coding[0].system = "http://terminology.hl7.org/CodeSystem/payeetype"
* payee.type.coding[0].code = #provider
* payee.type.coding[0].display = "Provider"
* payee.party.reference = "Organization/2910"
* payee.party.display = "TrueScript Pharmacy"
* claim.reference = "Claim/2912"
* claim.display = "Claim for Alice Dominguez Gibson"
* claimResponse.reference = "ClaimResponse/2913"
* claimResponse.display = "Alice Dominguez Gibson ClaimResponse"
// * supportingInfo[0].sequence = 1
// * supportingInfo[0].category.coding[0].system = "http://terminology.hl7.org/CodeSystem/claiminformationcategory"
// * supportingInfo[0].category.coding[0].code = #info
// * supportingInfo[0].category.coding[0].display = "Information"
// * supportingInfo[0].code.coding[0].system = "http://www.nlm.nih.gov/research/umls/rxnorm"
// * supportingInfo[0].code.coding[0].code = #860518
// * supportingInfo[0].code.coding[0].display = "24 HR carvedilol phosphate 20 MG Extended Release Oral Capsule [Coreg]"
// * supportingInfo[1].sequence = 2
// * supportingInfo[1].category.coding[0].system = "http://terminology.hl7.org/CodeSystem/claiminformationcategory"
// * supportingInfo[1].category.coding[0].code = #info
// * supportingInfo[1].category.coding[0].display = "Information"
// * supportingInfo[1].code.coding[0].system = "http://www.nlm.nih.gov/research/umls/rxnorm"
// * supportingInfo[1].code.coding[0].code = #104416
// * supportingInfo[1].code.coding[0].display = "amLODIPine Besylate"
// * supportingInfo[2].sequence = 3
// * supportingInfo[2].category.coding[0].system = "http://terminology.hl7.org/CodeSystem/claiminformationcategory"
// * supportingInfo[2].category.coding[0].code = #info
// * supportingInfo[2].category.coding[0].display = "Information"
// * supportingInfo[2].code.coding[0].system = "http://www.nlm.nih.gov/research/umls/rxnorm"
// * supportingInfo[2].code.coding[0].code = #258337
// * supportingInfo[2].code.coding[0].display = "Hydrochlorothiazide / Triamterene"
* insurance[0].coverage.reference = "Coverage/65"
* insurance[0].coverage.display = "Alice Dominguez Gibson Coverage"
* item[0].sequence = 1
* item[0].informationSequence[0] = 1
* item[0].category.coding[0].system = "https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd"
* item[0].category.coding[0].code = #1
* item[0].category.coding[0].display = "Medical care"
// This should be an NDC Code!
* item[0].productOrService.coding[0].system = $FDANationalDrugCodeCS#860518 "24 HR carvedilol phosphate 20 MG Extended Release Oral Capsule [Coreg]"
* item[0].servicedPeriod.start = "2019-01-18T15:40:00-05:00"
* item[0].servicedPeriod.end = "2019-01-18T16:00:00-05:00"
* item[0].locationCodeableConcept.coding[0].system =  $CMSPlaceOfServiceCS#49 "Independent Clinic"
* item[0].quantity.value = 30
* item[0].unitPrice.value = 81.86
* item[0].unitPrice.currency = #USD
* item[0].net.value = 81.86
* item[0].net.currency = #USD
* item[0].adjudication[adjudicationamounttype][0].category = C4BBAdjudicationCS#coinsurance "Beneficiary Coinsurance Amount"
* item[0].adjudication[adjudicationamounttype][0].amount.value = 81.86
* item[0].adjudication[adjudicationamounttype][0].amount.currency = #USD
* item[0].adjudication[adjudicationamounttype][1].category = C4BBAdjudicationCS#paidtoprovider "Paid to provider"  
* item[0].adjudication[adjudicationamounttype][1].amount.value = 0.0
* item[0].adjudication[adjudicationamounttype][1].amount.currency = #USD
* item[0].adjudication[adjudicationamounttype][2].category = $HL7AdjudicationCS#submitted  "Submitted"
* item[0].adjudication[adjudicationamounttype][2].amount.value = 81.86
* item[0].adjudication[adjudicationamounttype][2].amount.currency = #USD  
// * item[0].adjudication[3].category = C4BBAdjudicationCS#allowed "Allowed"
// * item[0].adjudication[3].amount.value = 81.86
// * item[0].adjudication[3].amount.currency = #USD
// * item[0].adjudication[4].category.coding[0].system = "https://bluebutton.cms.gov/resources/codesystem/adjudication"
// * item[0].adjudication[4].category.coding[0].code = #https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd
// * item[0].adjudication[4].category.coding[0].display = "Line Processing Indicator Code"
// * item[0].adjudication[4].reason.coding[0].system = "https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd"
// * item[0].adjudication[4].reason.coding[0].code = #A
// * item[0].adjudication[4].reason.coding[0].display = "Allowed"
// * item[0].adjudication[5].category.coding[0].system = "https://bluebutton.cms.gov/resources/codesystem/adjudication"
// * item[0].adjudication[5].category.coding[0].code = #https://bluebutton.cms.gov/resources/variables/line_bene_ptb_ddctbl_amt
// * item[0].adjudication[5].category.coding[0].display = "Line Beneficiary Part B Deductible Amount"
// * item[0].adjudication[5].amount.value = 500.0
// * item[0].adjudication[5].amount.currency = #USD
* item[1].sequence = 2
* item[1].informationSequence[0] = 2
* item[1].category.coding[0].system = "https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd"
* item[1].category.coding[0].code = #1
* item[1].category.coding[0].display = "Medical care"
* item[1].productOrService.coding[0].system = "http://www.nlm.nih.gov/research/umls/rxnorm"
* item[1].productOrService.coding[0].code = #104416
* item[1].productOrService.coding[0].display = "amLODIPine Besylate"
* item[1].servicedPeriod.start = "2019-01-18T15:40:00-05:00"
* item[1].servicedPeriod.end = "2019-01-18T16:00:00-05:00"
* item[1].locationCodeableConcept.coding[0].system = "https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd"
* item[1].locationCodeableConcept.coding[0].code = #49
* item[1].locationCodeableConcept.coding[0].display = "Independent Clinic"
* item[1].quantity.value = 30
* item[1].unitPrice.value = 11.43
* item[1].unitPrice.currency = #USD
* item[1].net.value = 11.43
* item[1].net.currency = #USD
* item[1].adjudication[adjudicationamounttype][0].category = C4BBAdjudicationCS#coinsurance "Beneficiary Coinsurance Amount"
* item[1].adjudication[adjudicationamounttype][0].amount.value = 11.43
* item[1].adjudication[adjudicationamounttype][0].amount.currency = #USD
* item[1].adjudication[adjudicationamounttype][1].category = C4BBAdjudicationCS#paidtoprovider "Paid to provider"  
* item[1].adjudication[adjudicationamounttype][1].amount.value = 0.0
* item[1].adjudication[adjudicationamounttype][1].amount.currency = #USD
* item[1].adjudication[adjudicationamounttype][2].category = $HL7AdjudicationCS#submitted  "Submitted"
* item[1].adjudication[adjudicationamounttype][2].amount.value = 11.43
* item[1].adjudication[adjudicationamounttype][2].amount.currency = #USD   
// * item[2].adjudication[adjudicationamounttype][3].category = C4BBAdjudicationCS#allowed "Allowed"
// * item[1].adjudication[3].amount.value = 11.43
// * item[1].adjudication[3].amount.currency = #USD
// * item[1].adjudication[4].category.coding[0].system = "https://bluebutton.cms.gov/resources/codesystem/adjudication"
// * item[1].adjudication[4].category.coding[0].code = #https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd
// * item[1].adjudication[4].category.coding[0].display = "Line Processing Indicator Code"
// * item[1].adjudication[4].reason.coding[0].system = "https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd"
// * item[1].adjudication[4].reason.coding[0].code = #A
// * item[1].adjudication[4].reason.coding[0].display = "Allowed"
// * item[1].adjudication[5].category.coding[0].system = "https://bluebutton.cms.gov/resources/codesystem/adjudication"
// * item[1].adjudication[5].category.coding[0].code = #https://bluebutton.cms.gov/resources/variables/line_bene_ptb_ddctbl_amt
// * item[1].adjudication[5].category.coding[0].display = "Line Beneficiary Part B Deductible Amount"
// * item[1].adjudication[5].amount.value = 500.0
// * item[1].adjudication[5].amount.currency = #USD
* item[2].sequence = 3
* item[2].informationSequence[0] = 3
* item[2].category.coding[0].system = "https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd"
* item[2].category.coding[0].code = #1
* item[2].category.coding[0].display = "Medical care"
* item[2].productOrService.coding[0].system = "http://www.nlm.nih.gov/research/umls/rxnorm"
* item[2].productOrService.coding[0].code = #258337
* item[2].productOrService.coding[0].display = "Hydrochlorothiazide / Triamterene"
* item[2].servicedPeriod.start = "2019-01-18T15:40:00-05:00"
* item[2].servicedPeriod.end = "2019-01-18T16:00:00-05:00"
* item[2].locationCodeableConcept.coding[0].system = "https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd"
* item[2].locationCodeableConcept.coding[0].code = #49
* item[2].locationCodeableConcept.coding[0].display = "Independent Clinic"
* item[2].quantity.value = 30
* item[2].unitPrice.value = 4.08
* item[2].unitPrice.currency = #USD
* item[2].net.value = 4.08
* item[2].net.currency = #USD
* item[2].adjudication[adjudicationamounttype][0].category = C4BBAdjudicationCS#coinsurance "Beneficiary Coinsurance Amount"
* item[2].adjudication[adjudicationamounttype][0].amount.value = 4.08
* item[2].adjudication[adjudicationamounttype][0].amount.currency = #USD
* item[2].adjudication[adjudicationamounttype][1].category = C4BBAdjudicationCS#paidtoprovider "Paid to provider"  
* item[2].adjudication[adjudicationamounttype][1].amount.value = 0.0
* item[2].adjudication[adjudicationamounttype][1].amount.currency = #USD
* item[2].adjudication[adjudicationamounttype][2].category = $HL7AdjudicationCS#submitted  "Submitted"
* item[2].adjudication[adjudicationamounttype][2].amount.value = 4.08
* item[2].adjudication[adjudicationamounttype][2].amount.currency = #USD   
// * item[1].adjudication[3].category = C4BBAdjudicationCS#allowed "Allowed"
// * item[1].adjudication[3].amount.value = 4.08
// * item[1].adjudication[3].amount.currency = #USD
// * item[2].adjudication[4].category.coding[0].system = "https://bluebutton.cms.gov/resources/codesystem/adjudication"
// * item[2].adjudication[4].category.coding[0].code = #https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd
// * item[2].adjudication[4].category.coding[0].display = "Line Processing Indicator Code"
// * item[2].adjudication[4].reason.coding[0].system = "https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd"
// * item[2].adjudication[4].reason.coding[0].code = #A
// * item[2].adjudication[4].reason.coding[0].display = "Allowed"
// * item[2].adjudication[5].category.coding[0].system = "https://bluebutton.cms.gov/resources/codesystem/adjudication"
// * item[2].adjudication[5].category.coding[0].code = #https://bluebutton.cms.gov/resources/variables/line_bene_ptb_ddctbl_amt
// * item[2].adjudication[5].category.coding[0].display = "Line Beneficiary Part B Deductible Amount"
// * item[2].adjudication[5].amount.value = 500.0
// * item[2].adjudication[5].amount.currency = #USD
* total[adjudicationamounttype].category = $HL7AdjudicationCS#submitted
* total[adjudicationamounttype].amount.value = 97.37
* total[adjudicationamounttype].amount.currency = #USD
* total[inoutnetwork].category = C4BBAdjudicationCS#innetwork 
* total[inoutnetwork].amount.value = 0.00
* total[inoutnetwork].amount.currency = #USD
* payment.amount.value = 0.0
* payment.amount.currency = #USD
// Added since these were missing and required from original example
//* adjudication[inoutnetwork].category = C4BBAdjudicationCS#innetwork 
* provider.display = "Minute Pharmacy"
* insurance[0].focal = true
* insurance[0].coverage[0] = Reference(Coverage1)
* outcome = #complete 
// added as embellishments
//* supportingInfo[0].sequence = 1
* supportingInfo[0].category = ClaimInformationCategoryCS#billingnetworkcontractingstatus
* supportingInfo[0].code = #contracted 
* supportingInfo[0].sequence = 1
* supportingInfo[1].category = ClaimInformationCategoryCS#brandgenericcode   
* supportingInfo[1].code = NCPDPBrandGenericCodeCS#generic 
* supportingInfo[1].sequence = 2
* supportingInfo[2].category = ClaimInformationCategoryCS#refillnum
* supportingInfo[2].valueQuantity.value = 10
* supportingInfo[2].sequence = 3
* supportingInfo[3].category = ClaimInformationCategoryCS#dawcode       
* supportingInfo[3].code = NCPDPDispensedAsWrittenCS#brandOnly  
* supportingInfo[3].sequence = 4
* supportingInfo[4].category = ClaimInformationCategoryCS#clmrecvddate
* supportingInfo[4].timingDate = "2019-01-18"
* supportingInfo[4].sequence = 5
* supportingInfo[5].category = ClaimInformationCategoryCS#dayssupply
// Why doesn't this work?
//* supportingInfo[dayssupply][5].valueQuantity.value = 30
* supportingInfo[5].valueQuantity.value = 30
* supportingInfo[5].sequence = 6

