Instance: BBEobOutpatientFacility
InstanceOf: CARINBBExplanationOfBenefitOutpatientFacility
Description: "BBEoB from Jeff"
* meta.versionId = "1"
* meta.lastUpdated = "2020-07-23T16:04:04.584-04:00"
* meta.source = "#2Htk0DNoUEbccjg0"
* meta.profile[0] = Canonical(CARINBBExplanationOfBenefitOutpatientFacility)
// * text.div = "<div xmlns="http://www.w3.org/1999/xhtml">This is a simple narrative with only plain text</div>"
// * extension[0].url = "http://mihin.org/extension/copyright"
// * extension[0].valueString = "Copyright 2014-2020 Michigan Health Information Network Shared Services. Licensed under the Apache License, Version 2.0 (the 'License'); you may not use this file except in compliance with the License. You may obtain a copy of the License at  http://www.apache.org/licenses/LICENSE-2.0.  Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License."
// * extension[1].url = "https://bluebutton.cms.gov/assets/ig/StructureDefinition-bluebutton-outpatient-nch-profnl-cmpnt-chrg-amt-extension"
// * extension[1].valueMoney.value = 0.0
// * extension[1].valueMoney.currency = #USD
// * extension[2].url = "https://bluebutton.cms.gov/assets/ig/StructureDefinition-bluebutton-outpatient-nch-bene-ptb-ddctbl-amt-extension"
// * extension[2].valueMoney.value = 0.0
// * extension[2].valueMoney.currency = #USD
// * extension[3].url = "https://bluebutton.cms.gov/assets/ig/StructureDefinition-bluebutton-outpatient-nch-bene-ptb-coinsrnc-amt-extension"
// * extension[3].valueMoney.value = 0.0
// * extension[3].valueMoney.currency = #USD
// * extension[4].url = "https://bluebutton.cms.gov/assets/ig/StructureDefinition-bluebutton-outpatient-clm-op-prvdr-pmt-amt-extension"
// * extension[4].valueMoney.value = 0.0
// * extension[4].valueMoney.currency = #USD
// * extension[5].url = "https://bluebutton.cms.gov/assets/ig/StructureDefinition-bluebutton-outpatient-clm-op-bene-pmt-amt-extension"
// * extension[5].valueMoney.value = 0.0
// * extension[5].valueMoney.currency = #USD
// * extension[6].url = "https://bluebutton.cms.gov/assets/ig/StructureDefinition-bluebutton-outpatient-nch-bene-blood-ddctbl-lblty-am-extension"
// * extension[6].valueMoney.value = 0.0
// * extension[6].valueMoney.currency = #USD
// * extension[7].url = "https://bluebutton.cms.gov/assets/ig/StructureDefinition-bluebutton-outpatient-clm-mdcr-non-pmt-rsn-cd-extension"
// * extension[7].valueCoding.system = "https://bluebutton.cms.gov/assets/ig/CodeSystem-clm-mdcr-non-pmt-rsn-cd"
// * extension[7].valueCoding.code = #N
// * extension[7].valueCoding.display = "All other reasons for non-payment"
// * extension[8].url = "https://bluebutton.cms.gov/assets/ig/StructureDefinition-bluebutton-outpatient-prpayamt-extension"
// * extension[8].valueMoney.value = 0.0
// * extension[8].valueMoney.currency = #USD
// * extension[9].url = "https://bluebutton.cms.gov/assets/ig/StructureDefinition-bluebutton-outpatient-fi-num-extension"
// * extension[9].valueIdentifier.system = "https://bluebutton.cms.gov/assets/ig/CodeSystem-fi-num"
// * extension[9].valueIdentifier.value = 002000
* identifier[claimnumber][0].value = "8ceaca46-ba97-4748-bbf7-80a4d54dc978"
* identifier[claimnumber][0].system = "https://bluebutton.cms.gov/resources/variables/clm_id"
* identifier[claimnumber][0].use = #official
* identifier[claimnumber][0].type = $IdentifierTypeCS#cn 
* use = #claim 
* status = #active
// * identifier[0].use = "official"
// * identifier[0].system = "http://www.bcbs.com/fhir/ns/NamingSystem/explanationOfBenefit-identifier"
// * identifier[0].value = 79e23846-e517-4ef8-ba21-2a1994b48ffd
// * identifier[1].use = "official"
// * identifier[1].type.coding[0].system = "http://terminology.hl7.org/CodeSystem/v2-0203"
// * identifier[1].type.coding[0].code = #MB
// * identifier[1].type.coding[0].display = "Member Number"
// * identifier[1].system = "http://www.bcbs.com/fhir/ns/NamingSystem/patient-mb"
// * identifier[1].value = 527439-3712
// * identifier[2].use = "official"
// * identifier[2].type.coding[0].system = "http://terminology.hl7.org/CodeSystem/v2-0203"
// * identifier[2].type.coding[0].code = #MR
// * identifier[2].type.coding[0].display = "Medical Record Number"
// * identifier[2].system = "http://www.bcbs.com/fhir/ns/NamingSystem/patient-mrn"
// * identifier[2].value = bf49e36b-abc4-4ec1-95a9-6954fe5f8324
// * identifier[3].use = "official"
// * identifier[3].type.coding[0].system = "http://terminology.hl7.org/CodeSystem/v2-0203"
// * identifier[3].type.coding[0].code = #PT
// * identifier[3].type.coding[0].display = "Patient External Identifier"
// * identifier[3].system = "http://www.bcbs.com/fhir/ns/NamingSystem/patient-identifier"
// * identifier[3].value = 07e8540172dd44f8a397850788bf48cd
// * identifier[4].system = "https://bluebutton.cms.gov/resources/variables/clm_id"
// * identifier[4].value = 8ceaca46-ba97-4748-bbf7-80a4d54dc978
// * identifier[5].system = "https://bluebutton.cms.gov/resources/identifier/claim-group"
// * identifier[5].value = S1201
// * status = "active"
* type.coding[0].system = "http://terminology.hl7.org/CodeSystem/claim-type"
* type.coding[0].code = #institutional
* type.coding[0].display = "INSTITUTIONAL"
* patient.reference = "Patient/1656"
* patient.display = "Bobbie Dawn Avery"
// * billablePeriod.extension[0].url = "https://bluebutton.cms.gov/assets/ig/StructureDefinition-bluebutton-outpatient-claim-query-cd-extension"
// * billablePeriod.extension[0].valueCoding.system = "https://bluebutton.cms.gov/assets/ig/ValueSet-claim-query-cd"
// * billablePeriod.extension[0].valueCoding.code = #3
// * billablePeriod.extension[0].valueCoding.display = "Final Bill"
* billablePeriod.start = "2019-01-08T08:40:00-05:00"
* billablePeriod.end = "2020-01-08T08:40:00-05:00"
* created = "2019-01-08T09:00:00-05:00"
* insurer.reference = "Organization/9"
* insurer.display = "SilverCaid"
* payee.type.coding[0].system = "http://terminology.hl7.org/CodeSystem/payeetype"
* payee.type.coding[0].code = #provider
* payee.type.coding[0].display = "Provider"
* payee.party.reference = "Organization/2348"
* payee.party.display = "Bay Area Family Practice"
* claim.reference = "Claim/2744"
* claim.display = "Claim for Bobbie Dawn Avery"
* claimResponse.reference = "ClaimResponse/2745"
* claimResponse.display = "Bobbie Dawn Avery ClaimResponse"
* careTeam[0].sequence = 1
* careTeam[0].provider.reference = "Practitioner/2584"
* careTeam[0].provider.identifier.system = "http://hl7.org/fhir/sid/us-npi"
* careTeam[0].provider.identifier.value = "9999992908"
* careTeam[0].provider.display = "Larry Calvin Kirk MD"
* careTeam[0].responsible = true
* careTeam[0].role.coding[0].system = "http://hl7.org/fhir/ValueSet/claim-careteamrole"
* careTeam[0].role.coding[0].code = #primary
* careTeam[0].role.coding[0].display = "Primary provide"
* careTeam[0].qualification.coding[0].system = "http://nucc.org/provider-taxonomy"
* careTeam[0].qualification.coding[0].code = #207QA0000X
* careTeam[0].qualification.coding[0].display = "Adolescent Medicine"
// * supportingInfo[0].sequence = 1
// * supportingInfo[0].category.coding[0].system = "http://terminology.hl7.org/CodeSystem/claiminformationcategory"
// * supportingInfo[0].category.coding[0].code = #info
// * supportingInfo[0].category.coding[0].display = "Information"
// * supportingInfo[0].code.coding[0].system = "http://www.nlm.nih.gov/research/umls/rxnorm"
// * supportingInfo[0].code.coding[0].code = #1856546
// * supportingInfo[0].code.coding[0].display = "Kyleena 19.5 MG Intrauterine System"
* insurance[0].coverage.reference = "Coverage/1657"
* insurance[0].coverage.display = "Bobbie Dawn Avery Coverage"
* item[0].sequence = 1
* item[0].informationSequence[0] = 1
* item[0].category.coding[0].system = "https://bluebutton.cms.gov/resources/variables/line_cms_type_srvc_cd"
* item[0].category.coding[0].code = #1
* item[0].category.coding[0].display = "Medical care"
// * item[0].extension[0].url = "https://bluebutton.cms.gov/assets/ig/StructureDefinition-bluebutton-outpatient-rev-cntr-ndc-qty-extension"
// * item[0].extension[0].valueQuantity.value = 0
// * item[0].productOrService.extension[0].url = "https://bluebutton.cms.gov/assets/ig/StructureDefinition-bluebutton-outpatient-rev-cntr-ide-ndc-upc-num-extension"
// * item[0].productOrService.extension[0].valueCoding.system = "https://www.accessdata.fda.gov/scripts/cder/ndc"
// * item[0].productOrService.extension[0].valueCoding.code = #0624
// * item[0].productOrService.extension[0].valueCoding.display = "Dummy"
* item[0].productOrService.coding[0].system = "http://snomed.info/sct"    // Should be from CPTHCPCSProcedureCode
* item[0].productOrService.coding[0].code = #698314001
* item[0].productOrService.coding[0].display = "Consultation for treatment"
* item[0].servicedPeriod.start = "2019-01-08T08:40:00-05:00"
* item[0].servicedPeriod.end = "2019-01-08T09:00:00-05:00"
* item[0].locationCodeableConcept.coding[0].system = "https://bluebutton.cms.gov/resources/variables/line_place_of_srvc_cd"
* item[0].locationCodeableConcept.coding[0].code = #49
* item[0].locationCodeableConcept.coding[0].display = "Independent Clinic"
* item[0].quantity.value = 1
* item[0].unitPrice.value = 106.39
* item[0].unitPrice.currency = #USD
* item[0].net.value = 106.39
* item[0].net.currency = #USD
// * item[0].adjudication[0].category.coding[0].system = "https://bluebutton.cms.gov/resources/codesystem/adjudication"
// * item[0].adjudication[0].category.coding[0].code = #https://bluebutton.cms.gov/resources/variables/line_coinsrnc_amt
// * item[0].adjudication[0].category.coding[0].display = "Line Beneficiary Coinsurance Amount"
// * item[0].adjudication[0].amount.value = 106.39
// * item[0].adjudication[0].amount.currency = #USD
// * item[0].adjudication[1].category.coding[0].system = "https://bluebutton.cms.gov/resources/codesystem/adjudication"
// * item[0].adjudication[1].category.coding[0].code = #https://bluebutton.cms.gov/resources/variables/line_prvdr_pmt_amt
// * item[0].adjudication[1].category.coding[0].display = "Line Provider Payment Amount"
// * item[0].adjudication[1].amount.value = 0.0
// * item[0].adjudication[1].amount.currency = #USD
// * item[0].adjudication[2].category.coding[0].system = "https://bluebutton.cms.gov/resources/codesystem/adjudication"
// * item[0].adjudication[2].category.coding[0].code = #https://bluebutton.cms.gov/resources/variables/line_sbmtd_chrg_amt
// * item[0].adjudication[2].category.coding[0].display = "Line Submitted Charge Amount"
// * item[0].adjudication[2].amount.value = 106.39
// * item[0].adjudication[2].amount.currency = #USD
// * item[0].adjudication[3].category.coding[0].system = "https://bluebutton.cms.gov/resources/codesystem/adjudication"
// * item[0].adjudication[3].category.coding[0].code = #https://bluebutton.cms.gov/resources/variables/line_alowd_chrg_amt
// * item[0].adjudication[3].category.coding[0].display = "Line Allowed Charge Amount"
// * item[0].adjudication[3].amount.value = 106.39
// * item[0].adjudication[3].amount.currency = #USD
* item[0].adjudication[adjudicationamounttype][0].category = PayerAdjudicationCategoryCS#coinsurance "Beneficiary Coinsurance Amount"
* item[0].adjudication[adjudicationamounttype][0].amount.value = 81.86
* item[0].adjudication[adjudicationamounttype][0].amount.currency = #USD
* item[0].adjudication[adjudicationamounttype][1].category = PayerAdjudicationCategoryCS#paidtoprovider "Paid to provider"  
* item[0].adjudication[adjudicationamounttype][1].amount.value = 0.0
* item[0].adjudication[adjudicationamounttype][1].amount.currency = #USD
* item[0].adjudication[adjudicationamounttype][2].category = $HL7AdjudicationCS#submitted  "Submitted"
* item[0].adjudication[adjudicationamounttype][2].amount.value = 81.86
* item[0].adjudication[adjudicationamounttype][2].amount.currency = #USD  
// * item[0].adjudication[4].category.coding[0].system = "https://bluebutton.cms.gov/resources/codesystem/adjudication"
// * item[0].adjudication[4].category.coding[0].code = #https://bluebutton.cms.gov/resources/variables/line_prcsg_ind_cd
// * item[0].adjudication[4].category.coding[0].display = "Line Processing Indicator Code"
// * item[0].adjudication[5].category.coding[0].system = "https://bluebutton.cms.gov/resources/codesystem/adjudication"
// * item[0].adjudication[5].category.coding[0].code = #https://bluebutton.cms.gov/resources/variables/line_bene_ptb_ddctbl_amt
// * item[0].adjudication[5].category.coding[0].display = "Line Beneficiary Part B Deductible Amount"
// * item[0].adjudication[5].amount.value = 500.0
// * item[0].adjudication[5].amount.currency = #USD
// * item[1].extension[0].url = "https://bluebutton.cms.gov/assets/ig/StructureDefinition-bluebutton-outpatient-rev-cntr-ndc-qty-extension"
// * item[1].extension[0].valueQuantity.value = 0
//***********     Items must be a procedure (HCPCPS Procedure Code), not an RXNorm Code  *************
//***********     So Item two has been struck in its entirety  

* payment.amount.value = 0
* payment.amount.currency = #USD
// Added since these were missing and required from original example
* total[inoutnetwork][0].category = PayerAdjudicationCategoryCS#innetwork 
* total[adjudicationamounttype][1].category =  $HL7AdjudicationCS#submitted
* total[adjudicationamounttype][1].amount.value = 81.86
* total[adjudicationamounttype][1].amount.currency = #USD
* provider.display = "Bay Area Family Practice"
* insurance[0].focal = true
* insurance[0].coverage[0] = Reference(Coverage1)
* outcome = #complete 
* diagnosis[0].diagnosisCodeableConcept = http://hl7.org/fhir/sid/icd-10-cm#S06.0x1A
* diagnosis[0].type = PayerDiagnosisTypeCS#principal
* diagnosis[0].sequence = 1 
// added as embellishments
//* supportingInfo[0].sequence = 1
* supportingInfo[0].category = ClaimInformationCategoryCS#billingnetworkcontractingstatus
* supportingInfo[0].code = #contracted 
* supportingInfo[0].sequence = 1
